import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const logStep = (step: string, details?: any) => {
  console.log(`[ADMIN-CUSTOMERS] ${step}${details ? ` - ${JSON.stringify(details)}` : ''}`);
};

const LS_API = "https://api.lemonsqueezy.com/v1";

const lsFetch = async (path: string, options: RequestInit = {}) => {
  const key = Deno.env.get("LEMONSQUEEZY_API_KEY");
  if (!key) throw new Error("LEMONSQUEEZY_API_KEY not set");
  return fetch(`${LS_API}${path}`, {
    ...options,
    headers: {
      "Accept": "application/vnd.api+json",
      "Content-Type": "application/vnd.api+json",
      "Authorization": `Bearer ${key}`,
    },
  });
};

const VERIFIED_BADGE_SVG = `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM16.71 9.29L11 15L7.29 11.29L8.71 9.88L11 12.17L15.29 7.88L16.71 9.29Z" fill="#1DA1F2"/>
</svg>`;

const EMAIL_TEMPLATE = (name: string, verified: boolean, prices: string) => `
<div style="font-family: Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background-color: #f9f9f9;">
  <div style="background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
    <div style="text-align: center; margin-bottom: 20px;">
      <img src="https://console.aiplanet.io/images/logo-full.svg" alt="AI Planet Logo" style="width: 150px;">
    </div>
    <h2 style="color: #333; text-align: center;">Customer Details</h2>
    <p style="color: #666; text-align: center;">Here is the information for customer <strong>${name}</strong> ${verified ? VERIFIED_BADGE_SVG : ''}</p>
    <div style="margin-top: 20px;">
      ${prices}
    </div>
    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    <p style="color: #777; font-size: 12px; text-align: center;">This email was automatically generated by AI Planet.</p>
  </div>
</div>
`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: corsHeaders,
    });
  }

  try {
    const url = new URL(req.url);

    // Admin auth
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false } }
    );

    const token = req.headers.get("Authorization")?.replace("Bearer ", "");
    if (!token) throw new Error("No auth token");

    const { data: userData, error: userError } = await supabaseAdmin.auth.getUser(token);
    if (userError || !userData?.user) {
      console.error("Error getting user:", userError);
      throw new Error("Not authenticated");
    }

    const { data: roleData, error: roleError } = await supabaseAdmin
      .from("user_roles")
      .select("role")
      .eq("user_id", userData.user.id)
      .eq("role", "admin")
      .single();

    if (roleError || !roleData) {
      console.error("Error getting role:", roleError);
      throw new Error("Admin access required");
    }
    logStep("Admin verified", { user_id: userData.user.id });

    // List Prices
    if (url.pathname === "/admin/customers/prices") {
      const email = url.searchParams.get("email");
      if (!email) throw new Error("Missing email parameter");

      // 1. Get user from Supabase
      const { data: user, error: supaErr } = await supabaseAdmin
        .from("profiles")
        .select("id, full_name, is_email_verified")
        .eq("email", email)
        .single();

      if (supaErr) {
        console.error("Supabase error:", supaErr);
        return new Response(JSON.stringify({ error: "Error fetching user from Supabase" }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 500,
        });
      }
      if (!user) {
        return new Response(JSON.stringify({ error: "User not found in Supabase" }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 404,
        });
      }

      // 2. Get Lemon Squeezy customer ID from Supabase
      const { data: ls_customer_id, error: lsErr } = await supabaseAdmin
        .from("user_details")
        .select("ls_customer_id")
        .eq("user_id", user.id)
        .single();

      if (lsErr) {
        console.error("Supabase error:", lsErr);
        return new Response(JSON.stringify({ error: "Error fetching LS customer ID from Supabase" }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 500,
        });
      }
      if (!ls_customer_id?.ls_customer_id) {
        return new Response(JSON.stringify({ error: "Lemon Squeezy customer ID not found for this user" }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 404,
        });
      }

      // 3. List subscriptions for customer from Lemon Squeezy
      const subscriptionsRes = await lsFetch(
        `/subscriptions?filter[customer_id]=${ls_customer_id.ls_customer_id}&include=variant`
      );
      if (!subscriptionsRes.ok) {
        console.error("LS error:", await subscriptionsRes.text());
        return new Response(JSON.stringify({ error: "Error fetching subscriptions from Lemon Squeezy" }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 500,
        });
      }

      const subscriptionsData = await subscriptionsRes.json();
      const subscriptions = subscriptionsData?.data || [];
      const includedVariants = subscriptionsData?.included?.filter((item: any) => item.type === 'variants') || [];

      // 4. Format prices
      const prices = subscriptions.map((sub: any) => {
        const variantId = sub.relationships.variant.data.id;
        const variant = includedVariants.find((v: any) => v.id === variantId);
        const productName = variant ? variant.attributes.name : 'Unknown Product';
        const price = (sub.attributes.prorated === true) ? 'Free trial' : `$${(sub.attributes.monthly_price / 100).toFixed(2)}/month`;

        return `<p style="color: #555;">${productName}: <strong>${price}</strong></p>`;
      }).join('');

      // 5. Return HTML email
      const html = EMAIL_TEMPLATE(user.full_name, user.is_email_verified, prices);
      return new Response(html, {
        headers: { ...corsHeaders, "Content-Type": "text/html" },
      });
    }

    return new Response(JSON.stringify({ error: "Invalid endpoint" }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 400,
    });
  } catch (error) {
    console.error("General error:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
